# Generated by Django 4.1.7 on 2023-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naglowek', models.CharField(max_length=200)),
                ('tresc', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'Newsy',
                'ordering': ['-data'],
            },
        ),
    ]
