# Generated by Django 4.1.7 on 2023-05-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='filmy/postery')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
